//go:build ignore

// 执行: go run main.go 自定更新导入ervice
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

// WailsSvc 扫描出来的服务信息
type WailsSvc struct {
	StructName string // HttpService
}

// 模板：生成 internal/service/service.go
const wailsServiceTpl = `// Code generated by gen_wails_service.go; DO NOT EDIT.
package service

import "github.com/wailsapp/wails/v3/pkg/application"

// NewAppServices 初始化所有服务，组装容器
func NewAppServices() []application.Service {
	return []application.Service{
{{range .Svcs}}		application.NewService(&{{.StructName}}{}),
{{end}}	}
}
`

type RenderData struct {
	Svcs []WailsSvc
}

func main() {
	fmt.Println("开始自动生成 wails3 service.go")

	path, err := os.Getwd()
	if err != nil {
		fmt.Printf("获取工作目录失败: %v\n", err)
		return
	}
	var scanDir string
	if strings.Contains(path, "service") {
		scanDir = "../"
	} else {
		scanDir = filepath.Join(path, "internal", "service")
	}
	outFile := filepath.Join(scanDir, "service.go")
	// 目标扫描目录 internal/service
	files, err := GetFileNames(scanDir)
	if err != nil {
		fmt.Printf("读取目录失败 %v\n", err)
		return
	}

	var svcList []WailsSvc
	for _, fname := range files {
		// 匹配 *_service.go，跳过自身 service.go
		if fname == "service.go" {
			continue
		}
		if !strings.HasSuffix(fname, "_service.go") {
			continue
		}
		// http_service.go → http → HttpService
		base := strings.TrimSuffix(fname, "_service.go")
		structName := ToCamel(base) + "Service"
		svcList = append(svcList, WailsSvc{StructName: structName})
	}

	if len(svcList) == 0 {
		fmt.Println("未找到任何 *_service.go 文件，跳过生成")
		return
	}

	err = GenWailsService(svcList, outFile)
	if err != nil {
		fmt.Printf("生成失败: %v\n", err)
	} else {
		fmt.Printf("生成完成: %s\n", outFile)
	}
}

// GenWailsService 渲染模板输出service.go
func GenWailsService(svcs []WailsSvc, outFilePath string) error {
	tpl, err := template.New("wails_service").Parse(wailsServiceTpl)
	if err != nil {
		return err
	}

	data := RenderData{Svcs: svcs}
	f, err := os.Create(outFilePath)
	if err != nil {
		return err
	}
	defer f.Close()

	if err := tpl.Execute(f, data); err != nil {
		return err
	}
	return FormatGoFile(outFilePath)
}

// FormatGoFile gofmt格式化
func FormatGoFile(filePath string) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	blankLineReg := regexp.MustCompile(`\n{3,}`)
	content := blankLineReg.ReplaceAll(data, []byte("\n\n"))

	src, err := format.Source(content)
	if err != nil {
		return err
	}
	return os.WriteFile(filePath, src, 0644)
}

// GetFileNames 获取目录一级文件，排除文件夹
func GetFileNames(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var fileNames []string
	for _, e := range entries {
		if !e.IsDir() {
			fileNames = append(fileNames, e.Name())
		}
	}
	return fileNames, nil
}

// ToCamel snake_case → CamelCase
func ToCamel(s string) string {
	parts := strings.Split(s, "_")
	var res strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		res.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return res.String()
}
