// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	ModbusDevice      *modbusDevice
	ModbusPoint       *modbusPoint
	MqttConnection    *mqttConnection
	MqttMessage       *mqttMessage
	MqttMessageRecord *mqttMessageRecord
	MqttSubscription  *mqttSubscription
	MqttTopicRecord   *mqttTopicRecord
	SqliteSequence    *sqliteSequence
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ModbusDevice = &Q.ModbusDevice
	ModbusPoint = &Q.ModbusPoint
	MqttConnection = &Q.MqttConnection
	MqttMessage = &Q.MqttMessage
	MqttMessageRecord = &Q.MqttMessageRecord
	MqttSubscription = &Q.MqttSubscription
	MqttTopicRecord = &Q.MqttTopicRecord
	SqliteSequence = &Q.SqliteSequence
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		ModbusDevice:      newModbusDevice(db, opts...),
		ModbusPoint:       newModbusPoint(db, opts...),
		MqttConnection:    newMqttConnection(db, opts...),
		MqttMessage:       newMqttMessage(db, opts...),
		MqttMessageRecord: newMqttMessageRecord(db, opts...),
		MqttSubscription:  newMqttSubscription(db, opts...),
		MqttTopicRecord:   newMqttTopicRecord(db, opts...),
		SqliteSequence:    newSqliteSequence(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ModbusDevice      modbusDevice
	ModbusPoint       modbusPoint
	MqttConnection    mqttConnection
	MqttMessage       mqttMessage
	MqttMessageRecord mqttMessageRecord
	MqttSubscription  mqttSubscription
	MqttTopicRecord   mqttTopicRecord
	SqliteSequence    sqliteSequence
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		ModbusDevice:      q.ModbusDevice.clone(db),
		ModbusPoint:       q.ModbusPoint.clone(db),
		MqttConnection:    q.MqttConnection.clone(db),
		MqttMessage:       q.MqttMessage.clone(db),
		MqttMessageRecord: q.MqttMessageRecord.clone(db),
		MqttSubscription:  q.MqttSubscription.clone(db),
		MqttTopicRecord:   q.MqttTopicRecord.clone(db),
		SqliteSequence:    q.SqliteSequence.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		ModbusDevice:      q.ModbusDevice.replaceDB(db),
		ModbusPoint:       q.ModbusPoint.replaceDB(db),
		MqttConnection:    q.MqttConnection.replaceDB(db),
		MqttMessage:       q.MqttMessage.replaceDB(db),
		MqttMessageRecord: q.MqttMessageRecord.replaceDB(db),
		MqttSubscription:  q.MqttSubscription.replaceDB(db),
		MqttTopicRecord:   q.MqttTopicRecord.replaceDB(db),
		SqliteSequence:    q.SqliteSequence.replaceDB(db),
	}
}

type queryCtx struct {
	ModbusDevice      IModbusDeviceDo
	ModbusPoint       IModbusPointDo
	MqttConnection    IMqttConnectionDo
	MqttMessage       IMqttMessageDo
	MqttMessageRecord IMqttMessageRecordDo
	MqttSubscription  IMqttSubscriptionDo
	MqttTopicRecord   IMqttTopicRecordDo
	SqliteSequence    ISqliteSequenceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ModbusDevice:      q.ModbusDevice.WithContext(ctx),
		ModbusPoint:       q.ModbusPoint.WithContext(ctx),
		MqttConnection:    q.MqttConnection.WithContext(ctx),
		MqttMessage:       q.MqttMessage.WithContext(ctx),
		MqttMessageRecord: q.MqttMessageRecord.WithContext(ctx),
		MqttSubscription:  q.MqttSubscription.WithContext(ctx),
		MqttTopicRecord:   q.MqttTopicRecord.WithContext(ctx),
		SqliteSequence:    q.SqliteSequence.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
