// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/internal/dao/model"
)

func newModbusPoint(db *gorm.DB, opts ...gen.DOOption) modbusPoint {
	_modbusPoint := modbusPoint{}

	_modbusPoint.modbusPointDo.UseDB(db, opts...)
	_modbusPoint.modbusPointDo.UseModel(&model.ModbusPoint{})

	tableName := _modbusPoint.modbusPointDo.TableName()
	_modbusPoint.ALL = field.NewAsterisk(tableName)
	_modbusPoint.ID = field.NewInt32(tableName, "id")
	_modbusPoint.DeviceID = field.NewInt32(tableName, "device_id")
	_modbusPoint.Name = field.NewString(tableName, "name")
	_modbusPoint.RegisterType = field.NewString(tableName, "register_type")
	_modbusPoint.Address = field.NewInt32(tableName, "address")
	_modbusPoint.Quantity = field.NewInt32(tableName, "quantity")
	_modbusPoint.DataType = field.NewString(tableName, "data_type")
	_modbusPoint.Scale = field.NewFloat64(tableName, "scale")
	_modbusPoint.Offset_ = field.NewFloat64(tableName, "offset")
	_modbusPoint.Unit = field.NewString(tableName, "unit")
	_modbusPoint.TopicOverride = field.NewString(tableName, "topic_override")
	_modbusPoint.OnlyOnChange = field.NewInt32(tableName, "only_on_change")
	_modbusPoint.Enabled = field.NewInt32(tableName, "enabled")
	_modbusPoint.Sort = field.NewInt32(tableName, "sort")
	_modbusPoint.CreatedAt = field.NewTime(tableName, "created_at")
	_modbusPoint.UpdatedAt = field.NewTime(tableName, "updated_at")

	_modbusPoint.fillFieldMap()

	return _modbusPoint
}

type modbusPoint struct {
	modbusPointDo

	ALL           field.Asterisk
	ID            field.Int32
	DeviceID      field.Int32
	Name          field.String
	RegisterType  field.String
	Address       field.Int32
	Quantity      field.Int32
	DataType      field.String
	Scale         field.Float64
	Offset_       field.Float64
	Unit          field.String
	TopicOverride field.String
	OnlyOnChange  field.Int32
	Enabled       field.Int32
	Sort          field.Int32
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (m modbusPoint) Table(newTableName string) *modbusPoint {
	m.modbusPointDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m modbusPoint) As(alias string) *modbusPoint {
	m.modbusPointDo.DO = *(m.modbusPointDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *modbusPoint) updateTableName(table string) *modbusPoint {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.DeviceID = field.NewInt32(table, "device_id")
	m.Name = field.NewString(table, "name")
	m.RegisterType = field.NewString(table, "register_type")
	m.Address = field.NewInt32(table, "address")
	m.Quantity = field.NewInt32(table, "quantity")
	m.DataType = field.NewString(table, "data_type")
	m.Scale = field.NewFloat64(table, "scale")
	m.Offset_ = field.NewFloat64(table, "offset")
	m.Unit = field.NewString(table, "unit")
	m.TopicOverride = field.NewString(table, "topic_override")
	m.OnlyOnChange = field.NewInt32(table, "only_on_change")
	m.Enabled = field.NewInt32(table, "enabled")
	m.Sort = field.NewInt32(table, "sort")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *modbusPoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *modbusPoint) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 16)
	m.fieldMap["id"] = m.ID
	m.fieldMap["device_id"] = m.DeviceID
	m.fieldMap["name"] = m.Name
	m.fieldMap["register_type"] = m.RegisterType
	m.fieldMap["address"] = m.Address
	m.fieldMap["quantity"] = m.Quantity
	m.fieldMap["data_type"] = m.DataType
	m.fieldMap["scale"] = m.Scale
	m.fieldMap["offset"] = m.Offset_
	m.fieldMap["unit"] = m.Unit
	m.fieldMap["topic_override"] = m.TopicOverride
	m.fieldMap["only_on_change"] = m.OnlyOnChange
	m.fieldMap["enabled"] = m.Enabled
	m.fieldMap["sort"] = m.Sort
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m modbusPoint) clone(db *gorm.DB) modbusPoint {
	m.modbusPointDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m modbusPoint) replaceDB(db *gorm.DB) modbusPoint {
	m.modbusPointDo.ReplaceDB(db)
	return m
}

type modbusPointDo struct{ gen.DO }

type IModbusPointDo interface {
	gen.SubQuery
	Debug() IModbusPointDo
	WithContext(ctx context.Context) IModbusPointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IModbusPointDo
	WriteDB() IModbusPointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IModbusPointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IModbusPointDo
	Not(conds ...gen.Condition) IModbusPointDo
	Or(conds ...gen.Condition) IModbusPointDo
	Select(conds ...field.Expr) IModbusPointDo
	Where(conds ...gen.Condition) IModbusPointDo
	Order(conds ...field.Expr) IModbusPointDo
	Distinct(cols ...field.Expr) IModbusPointDo
	Omit(cols ...field.Expr) IModbusPointDo
	Join(table schema.Tabler, on ...field.Expr) IModbusPointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IModbusPointDo
	RightJoin(table schema.Tabler, on ...field.Expr) IModbusPointDo
	Group(cols ...field.Expr) IModbusPointDo
	Having(conds ...gen.Condition) IModbusPointDo
	Limit(limit int) IModbusPointDo
	Offset(offset int) IModbusPointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IModbusPointDo
	Unscoped() IModbusPointDo
	Create(values ...*model.ModbusPoint) error
	CreateInBatches(values []*model.ModbusPoint, batchSize int) error
	Save(values ...*model.ModbusPoint) error
	First() (*model.ModbusPoint, error)
	Take() (*model.ModbusPoint, error)
	Last() (*model.ModbusPoint, error)
	Find() ([]*model.ModbusPoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModbusPoint, err error)
	FindInBatches(result *[]*model.ModbusPoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ModbusPoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IModbusPointDo
	Assign(attrs ...field.AssignExpr) IModbusPointDo
	Joins(fields ...field.RelationField) IModbusPointDo
	Preload(fields ...field.RelationField) IModbusPointDo
	FirstOrInit() (*model.ModbusPoint, error)
	FirstOrCreate() (*model.ModbusPoint, error)
	FindByPage(offset int, limit int) (result []*model.ModbusPoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IModbusPointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m modbusPointDo) Debug() IModbusPointDo {
	return m.withDO(m.DO.Debug())
}

func (m modbusPointDo) WithContext(ctx context.Context) IModbusPointDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modbusPointDo) ReadDB() IModbusPointDo {
	return m.Clauses(dbresolver.Read)
}

func (m modbusPointDo) WriteDB() IModbusPointDo {
	return m.Clauses(dbresolver.Write)
}

func (m modbusPointDo) Session(config *gorm.Session) IModbusPointDo {
	return m.withDO(m.DO.Session(config))
}

func (m modbusPointDo) Clauses(conds ...clause.Expression) IModbusPointDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modbusPointDo) Returning(value interface{}, columns ...string) IModbusPointDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modbusPointDo) Not(conds ...gen.Condition) IModbusPointDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modbusPointDo) Or(conds ...gen.Condition) IModbusPointDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modbusPointDo) Select(conds ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modbusPointDo) Where(conds ...gen.Condition) IModbusPointDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modbusPointDo) Order(conds ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modbusPointDo) Distinct(cols ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modbusPointDo) Omit(cols ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modbusPointDo) Join(table schema.Tabler, on ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modbusPointDo) LeftJoin(table schema.Tabler, on ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modbusPointDo) RightJoin(table schema.Tabler, on ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modbusPointDo) Group(cols ...field.Expr) IModbusPointDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modbusPointDo) Having(conds ...gen.Condition) IModbusPointDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modbusPointDo) Limit(limit int) IModbusPointDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modbusPointDo) Offset(offset int) IModbusPointDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modbusPointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IModbusPointDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modbusPointDo) Unscoped() IModbusPointDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modbusPointDo) Create(values ...*model.ModbusPoint) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modbusPointDo) CreateInBatches(values []*model.ModbusPoint, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modbusPointDo) Save(values ...*model.ModbusPoint) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modbusPointDo) First() (*model.ModbusPoint, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusPoint), nil
	}
}

func (m modbusPointDo) Take() (*model.ModbusPoint, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusPoint), nil
	}
}

func (m modbusPointDo) Last() (*model.ModbusPoint, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusPoint), nil
	}
}

func (m modbusPointDo) Find() ([]*model.ModbusPoint, error) {
	result, err := m.DO.Find()
	return result.([]*model.ModbusPoint), err
}

func (m modbusPointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModbusPoint, err error) {
	buf := make([]*model.ModbusPoint, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modbusPointDo) FindInBatches(result *[]*model.ModbusPoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modbusPointDo) Attrs(attrs ...field.AssignExpr) IModbusPointDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modbusPointDo) Assign(attrs ...field.AssignExpr) IModbusPointDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modbusPointDo) Joins(fields ...field.RelationField) IModbusPointDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modbusPointDo) Preload(fields ...field.RelationField) IModbusPointDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modbusPointDo) FirstOrInit() (*model.ModbusPoint, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusPoint), nil
	}
}

func (m modbusPointDo) FirstOrCreate() (*model.ModbusPoint, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusPoint), nil
	}
}

func (m modbusPointDo) FindByPage(offset int, limit int) (result []*model.ModbusPoint, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modbusPointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modbusPointDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modbusPointDo) Delete(models ...*model.ModbusPoint) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modbusPointDo) withDO(do gen.Dao) *modbusPointDo {
	m.DO = *do.(*gen.DO)
	return m
}
