// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/internal/dao/model"
)

func newModbusDevice(db *gorm.DB, opts ...gen.DOOption) modbusDevice {
	_modbusDevice := modbusDevice{}

	_modbusDevice.modbusDeviceDo.UseDB(db, opts...)
	_modbusDevice.modbusDeviceDo.UseModel(&model.ModbusDevice{})

	tableName := _modbusDevice.modbusDeviceDo.TableName()
	_modbusDevice.ALL = field.NewAsterisk(tableName)
	_modbusDevice.ID = field.NewInt32(tableName, "id")
	_modbusDevice.Name = field.NewString(tableName, "name")
	_modbusDevice.Protocol = field.NewString(tableName, "protocol")
	_modbusDevice.Host = field.NewString(tableName, "host")
	_modbusDevice.Port = field.NewInt32(tableName, "port")
	_modbusDevice.SlaveID = field.NewInt32(tableName, "slave_id")
	_modbusDevice.SerialPort = field.NewString(tableName, "serial_port")
	_modbusDevice.BaudRate = field.NewInt32(tableName, "baud_rate")
	_modbusDevice.DataBits = field.NewInt32(tableName, "data_bits")
	_modbusDevice.StopBits = field.NewInt32(tableName, "stop_bits")
	_modbusDevice.Parity = field.NewString(tableName, "parity")
	_modbusDevice.PollInterval = field.NewInt32(tableName, "poll_interval")
	_modbusDevice.Timeout = field.NewInt32(tableName, "timeout")
	_modbusDevice.RetryCount = field.NewInt32(tableName, "retry_count")
	_modbusDevice.ByteOrder = field.NewString(tableName, "byte_order")
	_modbusDevice.WordOrder = field.NewString(tableName, "word_order")
	_modbusDevice.BrokerConnectionID = field.NewInt32(tableName, "broker_connection_id")
	_modbusDevice.TopicPrefix = field.NewString(tableName, "topic_prefix")
	_modbusDevice.Qos = field.NewInt32(tableName, "qos")
	_modbusDevice.Retain = field.NewInt32(tableName, "retain")
	_modbusDevice.AlarmTopic = field.NewString(tableName, "alarm_topic")
	_modbusDevice.Enabled = field.NewInt32(tableName, "enabled")
	_modbusDevice.CreatedAt = field.NewTime(tableName, "created_at")
	_modbusDevice.UpdatedAt = field.NewTime(tableName, "updated_at")

	_modbusDevice.fillFieldMap()

	return _modbusDevice
}

type modbusDevice struct {
	modbusDeviceDo

	ALL                field.Asterisk
	ID                 field.Int32
	Name               field.String
	Protocol           field.String
	Host               field.String
	Port               field.Int32
	SlaveID            field.Int32
	SerialPort         field.String
	BaudRate           field.Int32
	DataBits           field.Int32
	StopBits           field.Int32
	Parity             field.String
	PollInterval       field.Int32
	Timeout            field.Int32
	RetryCount         field.Int32
	ByteOrder          field.String
	WordOrder          field.String
	BrokerConnectionID field.Int32
	TopicPrefix        field.String
	Qos                field.Int32
	Retain             field.Int32
	AlarmTopic         field.String
	Enabled            field.Int32
	CreatedAt          field.Time
	UpdatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (m modbusDevice) Table(newTableName string) *modbusDevice {
	m.modbusDeviceDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m modbusDevice) As(alias string) *modbusDevice {
	m.modbusDeviceDo.DO = *(m.modbusDeviceDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *modbusDevice) updateTableName(table string) *modbusDevice {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.Name = field.NewString(table, "name")
	m.Protocol = field.NewString(table, "protocol")
	m.Host = field.NewString(table, "host")
	m.Port = field.NewInt32(table, "port")
	m.SlaveID = field.NewInt32(table, "slave_id")
	m.SerialPort = field.NewString(table, "serial_port")
	m.BaudRate = field.NewInt32(table, "baud_rate")
	m.DataBits = field.NewInt32(table, "data_bits")
	m.StopBits = field.NewInt32(table, "stop_bits")
	m.Parity = field.NewString(table, "parity")
	m.PollInterval = field.NewInt32(table, "poll_interval")
	m.Timeout = field.NewInt32(table, "timeout")
	m.RetryCount = field.NewInt32(table, "retry_count")
	m.ByteOrder = field.NewString(table, "byte_order")
	m.WordOrder = field.NewString(table, "word_order")
	m.BrokerConnectionID = field.NewInt32(table, "broker_connection_id")
	m.TopicPrefix = field.NewString(table, "topic_prefix")
	m.Qos = field.NewInt32(table, "qos")
	m.Retain = field.NewInt32(table, "retain")
	m.AlarmTopic = field.NewString(table, "alarm_topic")
	m.Enabled = field.NewInt32(table, "enabled")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *modbusDevice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *modbusDevice) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 24)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["protocol"] = m.Protocol
	m.fieldMap["host"] = m.Host
	m.fieldMap["port"] = m.Port
	m.fieldMap["slave_id"] = m.SlaveID
	m.fieldMap["serial_port"] = m.SerialPort
	m.fieldMap["baud_rate"] = m.BaudRate
	m.fieldMap["data_bits"] = m.DataBits
	m.fieldMap["stop_bits"] = m.StopBits
	m.fieldMap["parity"] = m.Parity
	m.fieldMap["poll_interval"] = m.PollInterval
	m.fieldMap["timeout"] = m.Timeout
	m.fieldMap["retry_count"] = m.RetryCount
	m.fieldMap["byte_order"] = m.ByteOrder
	m.fieldMap["word_order"] = m.WordOrder
	m.fieldMap["broker_connection_id"] = m.BrokerConnectionID
	m.fieldMap["topic_prefix"] = m.TopicPrefix
	m.fieldMap["qos"] = m.Qos
	m.fieldMap["retain"] = m.Retain
	m.fieldMap["alarm_topic"] = m.AlarmTopic
	m.fieldMap["enabled"] = m.Enabled
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m modbusDevice) clone(db *gorm.DB) modbusDevice {
	m.modbusDeviceDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m modbusDevice) replaceDB(db *gorm.DB) modbusDevice {
	m.modbusDeviceDo.ReplaceDB(db)
	return m
}

type modbusDeviceDo struct{ gen.DO }

type IModbusDeviceDo interface {
	gen.SubQuery
	Debug() IModbusDeviceDo
	WithContext(ctx context.Context) IModbusDeviceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IModbusDeviceDo
	WriteDB() IModbusDeviceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IModbusDeviceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IModbusDeviceDo
	Not(conds ...gen.Condition) IModbusDeviceDo
	Or(conds ...gen.Condition) IModbusDeviceDo
	Select(conds ...field.Expr) IModbusDeviceDo
	Where(conds ...gen.Condition) IModbusDeviceDo
	Order(conds ...field.Expr) IModbusDeviceDo
	Distinct(cols ...field.Expr) IModbusDeviceDo
	Omit(cols ...field.Expr) IModbusDeviceDo
	Join(table schema.Tabler, on ...field.Expr) IModbusDeviceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IModbusDeviceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IModbusDeviceDo
	Group(cols ...field.Expr) IModbusDeviceDo
	Having(conds ...gen.Condition) IModbusDeviceDo
	Limit(limit int) IModbusDeviceDo
	Offset(offset int) IModbusDeviceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IModbusDeviceDo
	Unscoped() IModbusDeviceDo
	Create(values ...*model.ModbusDevice) error
	CreateInBatches(values []*model.ModbusDevice, batchSize int) error
	Save(values ...*model.ModbusDevice) error
	First() (*model.ModbusDevice, error)
	Take() (*model.ModbusDevice, error)
	Last() (*model.ModbusDevice, error)
	Find() ([]*model.ModbusDevice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModbusDevice, err error)
	FindInBatches(result *[]*model.ModbusDevice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ModbusDevice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IModbusDeviceDo
	Assign(attrs ...field.AssignExpr) IModbusDeviceDo
	Joins(fields ...field.RelationField) IModbusDeviceDo
	Preload(fields ...field.RelationField) IModbusDeviceDo
	FirstOrInit() (*model.ModbusDevice, error)
	FirstOrCreate() (*model.ModbusDevice, error)
	FindByPage(offset int, limit int) (result []*model.ModbusDevice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IModbusDeviceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m modbusDeviceDo) Debug() IModbusDeviceDo {
	return m.withDO(m.DO.Debug())
}

func (m modbusDeviceDo) WithContext(ctx context.Context) IModbusDeviceDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modbusDeviceDo) ReadDB() IModbusDeviceDo {
	return m.Clauses(dbresolver.Read)
}

func (m modbusDeviceDo) WriteDB() IModbusDeviceDo {
	return m.Clauses(dbresolver.Write)
}

func (m modbusDeviceDo) Session(config *gorm.Session) IModbusDeviceDo {
	return m.withDO(m.DO.Session(config))
}

func (m modbusDeviceDo) Clauses(conds ...clause.Expression) IModbusDeviceDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modbusDeviceDo) Returning(value interface{}, columns ...string) IModbusDeviceDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modbusDeviceDo) Not(conds ...gen.Condition) IModbusDeviceDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modbusDeviceDo) Or(conds ...gen.Condition) IModbusDeviceDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modbusDeviceDo) Select(conds ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modbusDeviceDo) Where(conds ...gen.Condition) IModbusDeviceDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modbusDeviceDo) Order(conds ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modbusDeviceDo) Distinct(cols ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modbusDeviceDo) Omit(cols ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modbusDeviceDo) Join(table schema.Tabler, on ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modbusDeviceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modbusDeviceDo) RightJoin(table schema.Tabler, on ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modbusDeviceDo) Group(cols ...field.Expr) IModbusDeviceDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modbusDeviceDo) Having(conds ...gen.Condition) IModbusDeviceDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modbusDeviceDo) Limit(limit int) IModbusDeviceDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modbusDeviceDo) Offset(offset int) IModbusDeviceDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modbusDeviceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IModbusDeviceDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modbusDeviceDo) Unscoped() IModbusDeviceDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modbusDeviceDo) Create(values ...*model.ModbusDevice) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modbusDeviceDo) CreateInBatches(values []*model.ModbusDevice, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modbusDeviceDo) Save(values ...*model.ModbusDevice) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modbusDeviceDo) First() (*model.ModbusDevice, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusDevice), nil
	}
}

func (m modbusDeviceDo) Take() (*model.ModbusDevice, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusDevice), nil
	}
}

func (m modbusDeviceDo) Last() (*model.ModbusDevice, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusDevice), nil
	}
}

func (m modbusDeviceDo) Find() ([]*model.ModbusDevice, error) {
	result, err := m.DO.Find()
	return result.([]*model.ModbusDevice), err
}

func (m modbusDeviceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModbusDevice, err error) {
	buf := make([]*model.ModbusDevice, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modbusDeviceDo) FindInBatches(result *[]*model.ModbusDevice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modbusDeviceDo) Attrs(attrs ...field.AssignExpr) IModbusDeviceDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modbusDeviceDo) Assign(attrs ...field.AssignExpr) IModbusDeviceDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modbusDeviceDo) Joins(fields ...field.RelationField) IModbusDeviceDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modbusDeviceDo) Preload(fields ...field.RelationField) IModbusDeviceDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modbusDeviceDo) FirstOrInit() (*model.ModbusDevice, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusDevice), nil
	}
}

func (m modbusDeviceDo) FirstOrCreate() (*model.ModbusDevice, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModbusDevice), nil
	}
}

func (m modbusDeviceDo) FindByPage(offset int, limit int) (result []*model.ModbusDevice, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modbusDeviceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modbusDeviceDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modbusDeviceDo) Delete(models ...*model.ModbusDevice) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modbusDeviceDo) withDO(do gen.Dao) *modbusDeviceDo {
	m.DO = *do.(*gen.DO)
	return m
}
