// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/internal/dao/model"
)

func newMqttMessageRecord(db *gorm.DB, opts ...gen.DOOption) mqttMessageRecord {
	_mqttMessageRecord := mqttMessageRecord{}

	_mqttMessageRecord.mqttMessageRecordDo.UseDB(db, opts...)
	_mqttMessageRecord.mqttMessageRecordDo.UseModel(&model.MqttMessageRecord{})

	tableName := _mqttMessageRecord.mqttMessageRecordDo.TableName()
	_mqttMessageRecord.ALL = field.NewAsterisk(tableName)
	_mqttMessageRecord.ID = field.NewInt32(tableName, "id")
	_mqttMessageRecord.Payload = field.NewString(tableName, "payload")
	_mqttMessageRecord.PayloadType = field.NewString(tableName, "payload_type")
	_mqttMessageRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_mqttMessageRecord.fillFieldMap()

	return _mqttMessageRecord
}

type mqttMessageRecord struct {
	mqttMessageRecordDo

	ALL         field.Asterisk
	ID          field.Int32
	Payload     field.String
	PayloadType field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m mqttMessageRecord) Table(newTableName string) *mqttMessageRecord {
	m.mqttMessageRecordDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mqttMessageRecord) As(alias string) *mqttMessageRecord {
	m.mqttMessageRecordDo.DO = *(m.mqttMessageRecordDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mqttMessageRecord) updateTableName(table string) *mqttMessageRecord {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.Payload = field.NewString(table, "payload")
	m.PayloadType = field.NewString(table, "payload_type")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *mqttMessageRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mqttMessageRecord) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["id"] = m.ID
	m.fieldMap["payload"] = m.Payload
	m.fieldMap["payload_type"] = m.PayloadType
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m mqttMessageRecord) clone(db *gorm.DB) mqttMessageRecord {
	m.mqttMessageRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mqttMessageRecord) replaceDB(db *gorm.DB) mqttMessageRecord {
	m.mqttMessageRecordDo.ReplaceDB(db)
	return m
}

type mqttMessageRecordDo struct{ gen.DO }

type IMqttMessageRecordDo interface {
	gen.SubQuery
	Debug() IMqttMessageRecordDo
	WithContext(ctx context.Context) IMqttMessageRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMqttMessageRecordDo
	WriteDB() IMqttMessageRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMqttMessageRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMqttMessageRecordDo
	Not(conds ...gen.Condition) IMqttMessageRecordDo
	Or(conds ...gen.Condition) IMqttMessageRecordDo
	Select(conds ...field.Expr) IMqttMessageRecordDo
	Where(conds ...gen.Condition) IMqttMessageRecordDo
	Order(conds ...field.Expr) IMqttMessageRecordDo
	Distinct(cols ...field.Expr) IMqttMessageRecordDo
	Omit(cols ...field.Expr) IMqttMessageRecordDo
	Join(table schema.Tabler, on ...field.Expr) IMqttMessageRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMqttMessageRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMqttMessageRecordDo
	Group(cols ...field.Expr) IMqttMessageRecordDo
	Having(conds ...gen.Condition) IMqttMessageRecordDo
	Limit(limit int) IMqttMessageRecordDo
	Offset(offset int) IMqttMessageRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttMessageRecordDo
	Unscoped() IMqttMessageRecordDo
	Create(values ...*model.MqttMessageRecord) error
	CreateInBatches(values []*model.MqttMessageRecord, batchSize int) error
	Save(values ...*model.MqttMessageRecord) error
	First() (*model.MqttMessageRecord, error)
	Take() (*model.MqttMessageRecord, error)
	Last() (*model.MqttMessageRecord, error)
	Find() ([]*model.MqttMessageRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttMessageRecord, err error)
	FindInBatches(result *[]*model.MqttMessageRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MqttMessageRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMqttMessageRecordDo
	Assign(attrs ...field.AssignExpr) IMqttMessageRecordDo
	Joins(fields ...field.RelationField) IMqttMessageRecordDo
	Preload(fields ...field.RelationField) IMqttMessageRecordDo
	FirstOrInit() (*model.MqttMessageRecord, error)
	FirstOrCreate() (*model.MqttMessageRecord, error)
	FindByPage(offset int, limit int) (result []*model.MqttMessageRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMqttMessageRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mqttMessageRecordDo) Debug() IMqttMessageRecordDo {
	return m.withDO(m.DO.Debug())
}

func (m mqttMessageRecordDo) WithContext(ctx context.Context) IMqttMessageRecordDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mqttMessageRecordDo) ReadDB() IMqttMessageRecordDo {
	return m.Clauses(dbresolver.Read)
}

func (m mqttMessageRecordDo) WriteDB() IMqttMessageRecordDo {
	return m.Clauses(dbresolver.Write)
}

func (m mqttMessageRecordDo) Session(config *gorm.Session) IMqttMessageRecordDo {
	return m.withDO(m.DO.Session(config))
}

func (m mqttMessageRecordDo) Clauses(conds ...clause.Expression) IMqttMessageRecordDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mqttMessageRecordDo) Returning(value interface{}, columns ...string) IMqttMessageRecordDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mqttMessageRecordDo) Not(conds ...gen.Condition) IMqttMessageRecordDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mqttMessageRecordDo) Or(conds ...gen.Condition) IMqttMessageRecordDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mqttMessageRecordDo) Select(conds ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mqttMessageRecordDo) Where(conds ...gen.Condition) IMqttMessageRecordDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mqttMessageRecordDo) Order(conds ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mqttMessageRecordDo) Distinct(cols ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mqttMessageRecordDo) Omit(cols ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mqttMessageRecordDo) Join(table schema.Tabler, on ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mqttMessageRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mqttMessageRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mqttMessageRecordDo) Group(cols ...field.Expr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mqttMessageRecordDo) Having(conds ...gen.Condition) IMqttMessageRecordDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mqttMessageRecordDo) Limit(limit int) IMqttMessageRecordDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mqttMessageRecordDo) Offset(offset int) IMqttMessageRecordDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mqttMessageRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttMessageRecordDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mqttMessageRecordDo) Unscoped() IMqttMessageRecordDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mqttMessageRecordDo) Create(values ...*model.MqttMessageRecord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mqttMessageRecordDo) CreateInBatches(values []*model.MqttMessageRecord, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mqttMessageRecordDo) Save(values ...*model.MqttMessageRecord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mqttMessageRecordDo) First() (*model.MqttMessageRecord, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessageRecord), nil
	}
}

func (m mqttMessageRecordDo) Take() (*model.MqttMessageRecord, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessageRecord), nil
	}
}

func (m mqttMessageRecordDo) Last() (*model.MqttMessageRecord, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessageRecord), nil
	}
}

func (m mqttMessageRecordDo) Find() ([]*model.MqttMessageRecord, error) {
	result, err := m.DO.Find()
	return result.([]*model.MqttMessageRecord), err
}

func (m mqttMessageRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttMessageRecord, err error) {
	buf := make([]*model.MqttMessageRecord, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mqttMessageRecordDo) FindInBatches(result *[]*model.MqttMessageRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mqttMessageRecordDo) Attrs(attrs ...field.AssignExpr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mqttMessageRecordDo) Assign(attrs ...field.AssignExpr) IMqttMessageRecordDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mqttMessageRecordDo) Joins(fields ...field.RelationField) IMqttMessageRecordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mqttMessageRecordDo) Preload(fields ...field.RelationField) IMqttMessageRecordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mqttMessageRecordDo) FirstOrInit() (*model.MqttMessageRecord, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessageRecord), nil
	}
}

func (m mqttMessageRecordDo) FirstOrCreate() (*model.MqttMessageRecord, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessageRecord), nil
	}
}

func (m mqttMessageRecordDo) FindByPage(offset int, limit int) (result []*model.MqttMessageRecord, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mqttMessageRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mqttMessageRecordDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mqttMessageRecordDo) Delete(models ...*model.MqttMessageRecord) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mqttMessageRecordDo) withDO(do gen.Dao) *mqttMessageRecordDo {
	m.DO = *do.(*gen.DO)
	return m
}
