// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/internal/dao/model"
)

func newMqttConnection(db *gorm.DB, opts ...gen.DOOption) mqttConnection {
	_mqttConnection := mqttConnection{}

	_mqttConnection.mqttConnectionDo.UseDB(db, opts...)
	_mqttConnection.mqttConnectionDo.UseModel(&model.MqttConnection{})

	tableName := _mqttConnection.mqttConnectionDo.TableName()
	_mqttConnection.ALL = field.NewAsterisk(tableName)
	_mqttConnection.ID = field.NewInt32(tableName, "id")
	_mqttConnection.Title = field.NewString(tableName, "title")
	_mqttConnection.Pid = field.NewInt32(tableName, "pid")
	_mqttConnection.IsGroup = field.NewInt32(tableName, "is_group")
	_mqttConnection.Protocol = field.NewString(tableName, "protocol")
	_mqttConnection.Host = field.NewString(tableName, "host")
	_mqttConnection.Port = field.NewString(tableName, "port")
	_mqttConnection.ClientID = field.NewString(tableName, "client_id")
	_mqttConnection.Path = field.NewString(tableName, "path")
	_mqttConnection.Username = field.NewString(tableName, "username")
	_mqttConnection.Password = field.NewString(tableName, "password")
	_mqttConnection.Ssl = field.NewInt32(tableName, "ssl")
	_mqttConnection.SslSecurity = field.NewInt32(tableName, "ssl_security")
	_mqttConnection.Alpn = field.NewString(tableName, "alpn")
	_mqttConnection.CertType = field.NewString(tableName, "cert_type")
	_mqttConnection.Ca = field.NewString(tableName, "ca")
	_mqttConnection.Cert = field.NewString(tableName, "cert")
	_mqttConnection.Key = field.NewString(tableName, "key")
	_mqttConnection.MqttVersion = field.NewString(tableName, "mqtt_version")
	_mqttConnection.ConnectTimeout = field.NewInt32(tableName, "connect_timeout")
	_mqttConnection.Keepalive = field.NewInt32(tableName, "keepalive")
	_mqttConnection.Reconnect = field.NewInt32(tableName, "reconnect")
	_mqttConnection.ReconnectPeriod = field.NewInt32(tableName, "reconnect_period")
	_mqttConnection.Clean = field.NewInt32(tableName, "clean")
	_mqttConnection.Properties = field.NewString(tableName, "properties")
	_mqttConnection.Will = field.NewString(tableName, "will")
	_mqttConnection.UserProperties = field.NewString(tableName, "user_properties")
	_mqttConnection.Weigh = field.NewInt32(tableName, "weigh")
	_mqttConnection.Connected = field.NewInt32(tableName, "connected")
	_mqttConnection.CreatedAt = field.NewTime(tableName, "created_at")
	_mqttConnection.UpdatedAt = field.NewTime(tableName, "updated_at")

	_mqttConnection.fillFieldMap()

	return _mqttConnection
}

type mqttConnection struct {
	mqttConnectionDo

	ALL             field.Asterisk
	ID              field.Int32
	Title           field.String
	Pid             field.Int32
	IsGroup         field.Int32
	Protocol        field.String
	Host            field.String
	Port            field.String
	ClientID        field.String
	Path            field.String
	Username        field.String
	Password        field.String
	Ssl             field.Int32
	SslSecurity     field.Int32
	Alpn            field.String
	CertType        field.String
	Ca              field.String
	Cert            field.String
	Key             field.String
	MqttVersion     field.String
	ConnectTimeout  field.Int32
	Keepalive       field.Int32
	Reconnect       field.Int32
	ReconnectPeriod field.Int32
	Clean           field.Int32
	Properties      field.String
	Will            field.String
	UserProperties  field.String
	Weigh           field.Int32
	Connected       field.Int32
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (m mqttConnection) Table(newTableName string) *mqttConnection {
	m.mqttConnectionDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mqttConnection) As(alias string) *mqttConnection {
	m.mqttConnectionDo.DO = *(m.mqttConnectionDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mqttConnection) updateTableName(table string) *mqttConnection {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.Title = field.NewString(table, "title")
	m.Pid = field.NewInt32(table, "pid")
	m.IsGroup = field.NewInt32(table, "is_group")
	m.Protocol = field.NewString(table, "protocol")
	m.Host = field.NewString(table, "host")
	m.Port = field.NewString(table, "port")
	m.ClientID = field.NewString(table, "client_id")
	m.Path = field.NewString(table, "path")
	m.Username = field.NewString(table, "username")
	m.Password = field.NewString(table, "password")
	m.Ssl = field.NewInt32(table, "ssl")
	m.SslSecurity = field.NewInt32(table, "ssl_security")
	m.Alpn = field.NewString(table, "alpn")
	m.CertType = field.NewString(table, "cert_type")
	m.Ca = field.NewString(table, "ca")
	m.Cert = field.NewString(table, "cert")
	m.Key = field.NewString(table, "key")
	m.MqttVersion = field.NewString(table, "mqtt_version")
	m.ConnectTimeout = field.NewInt32(table, "connect_timeout")
	m.Keepalive = field.NewInt32(table, "keepalive")
	m.Reconnect = field.NewInt32(table, "reconnect")
	m.ReconnectPeriod = field.NewInt32(table, "reconnect_period")
	m.Clean = field.NewInt32(table, "clean")
	m.Properties = field.NewString(table, "properties")
	m.Will = field.NewString(table, "will")
	m.UserProperties = field.NewString(table, "user_properties")
	m.Weigh = field.NewInt32(table, "weigh")
	m.Connected = field.NewInt32(table, "connected")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *mqttConnection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mqttConnection) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 31)
	m.fieldMap["id"] = m.ID
	m.fieldMap["title"] = m.Title
	m.fieldMap["pid"] = m.Pid
	m.fieldMap["is_group"] = m.IsGroup
	m.fieldMap["protocol"] = m.Protocol
	m.fieldMap["host"] = m.Host
	m.fieldMap["port"] = m.Port
	m.fieldMap["client_id"] = m.ClientID
	m.fieldMap["path"] = m.Path
	m.fieldMap["username"] = m.Username
	m.fieldMap["password"] = m.Password
	m.fieldMap["ssl"] = m.Ssl
	m.fieldMap["ssl_security"] = m.SslSecurity
	m.fieldMap["alpn"] = m.Alpn
	m.fieldMap["cert_type"] = m.CertType
	m.fieldMap["ca"] = m.Ca
	m.fieldMap["cert"] = m.Cert
	m.fieldMap["key"] = m.Key
	m.fieldMap["mqtt_version"] = m.MqttVersion
	m.fieldMap["connect_timeout"] = m.ConnectTimeout
	m.fieldMap["keepalive"] = m.Keepalive
	m.fieldMap["reconnect"] = m.Reconnect
	m.fieldMap["reconnect_period"] = m.ReconnectPeriod
	m.fieldMap["clean"] = m.Clean
	m.fieldMap["properties"] = m.Properties
	m.fieldMap["will"] = m.Will
	m.fieldMap["user_properties"] = m.UserProperties
	m.fieldMap["weigh"] = m.Weigh
	m.fieldMap["connected"] = m.Connected
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m mqttConnection) clone(db *gorm.DB) mqttConnection {
	m.mqttConnectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mqttConnection) replaceDB(db *gorm.DB) mqttConnection {
	m.mqttConnectionDo.ReplaceDB(db)
	return m
}

type mqttConnectionDo struct{ gen.DO }

type IMqttConnectionDo interface {
	gen.SubQuery
	Debug() IMqttConnectionDo
	WithContext(ctx context.Context) IMqttConnectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMqttConnectionDo
	WriteDB() IMqttConnectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMqttConnectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMqttConnectionDo
	Not(conds ...gen.Condition) IMqttConnectionDo
	Or(conds ...gen.Condition) IMqttConnectionDo
	Select(conds ...field.Expr) IMqttConnectionDo
	Where(conds ...gen.Condition) IMqttConnectionDo
	Order(conds ...field.Expr) IMqttConnectionDo
	Distinct(cols ...field.Expr) IMqttConnectionDo
	Omit(cols ...field.Expr) IMqttConnectionDo
	Join(table schema.Tabler, on ...field.Expr) IMqttConnectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMqttConnectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMqttConnectionDo
	Group(cols ...field.Expr) IMqttConnectionDo
	Having(conds ...gen.Condition) IMqttConnectionDo
	Limit(limit int) IMqttConnectionDo
	Offset(offset int) IMqttConnectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttConnectionDo
	Unscoped() IMqttConnectionDo
	Create(values ...*model.MqttConnection) error
	CreateInBatches(values []*model.MqttConnection, batchSize int) error
	Save(values ...*model.MqttConnection) error
	First() (*model.MqttConnection, error)
	Take() (*model.MqttConnection, error)
	Last() (*model.MqttConnection, error)
	Find() ([]*model.MqttConnection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttConnection, err error)
	FindInBatches(result *[]*model.MqttConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MqttConnection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMqttConnectionDo
	Assign(attrs ...field.AssignExpr) IMqttConnectionDo
	Joins(fields ...field.RelationField) IMqttConnectionDo
	Preload(fields ...field.RelationField) IMqttConnectionDo
	FirstOrInit() (*model.MqttConnection, error)
	FirstOrCreate() (*model.MqttConnection, error)
	FindByPage(offset int, limit int) (result []*model.MqttConnection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMqttConnectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mqttConnectionDo) Debug() IMqttConnectionDo {
	return m.withDO(m.DO.Debug())
}

func (m mqttConnectionDo) WithContext(ctx context.Context) IMqttConnectionDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mqttConnectionDo) ReadDB() IMqttConnectionDo {
	return m.Clauses(dbresolver.Read)
}

func (m mqttConnectionDo) WriteDB() IMqttConnectionDo {
	return m.Clauses(dbresolver.Write)
}

func (m mqttConnectionDo) Session(config *gorm.Session) IMqttConnectionDo {
	return m.withDO(m.DO.Session(config))
}

func (m mqttConnectionDo) Clauses(conds ...clause.Expression) IMqttConnectionDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mqttConnectionDo) Returning(value interface{}, columns ...string) IMqttConnectionDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mqttConnectionDo) Not(conds ...gen.Condition) IMqttConnectionDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mqttConnectionDo) Or(conds ...gen.Condition) IMqttConnectionDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mqttConnectionDo) Select(conds ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mqttConnectionDo) Where(conds ...gen.Condition) IMqttConnectionDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mqttConnectionDo) Order(conds ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mqttConnectionDo) Distinct(cols ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mqttConnectionDo) Omit(cols ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mqttConnectionDo) Join(table schema.Tabler, on ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mqttConnectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mqttConnectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mqttConnectionDo) Group(cols ...field.Expr) IMqttConnectionDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mqttConnectionDo) Having(conds ...gen.Condition) IMqttConnectionDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mqttConnectionDo) Limit(limit int) IMqttConnectionDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mqttConnectionDo) Offset(offset int) IMqttConnectionDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mqttConnectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttConnectionDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mqttConnectionDo) Unscoped() IMqttConnectionDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mqttConnectionDo) Create(values ...*model.MqttConnection) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mqttConnectionDo) CreateInBatches(values []*model.MqttConnection, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mqttConnectionDo) Save(values ...*model.MqttConnection) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mqttConnectionDo) First() (*model.MqttConnection, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttConnection), nil
	}
}

func (m mqttConnectionDo) Take() (*model.MqttConnection, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttConnection), nil
	}
}

func (m mqttConnectionDo) Last() (*model.MqttConnection, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttConnection), nil
	}
}

func (m mqttConnectionDo) Find() ([]*model.MqttConnection, error) {
	result, err := m.DO.Find()
	return result.([]*model.MqttConnection), err
}

func (m mqttConnectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttConnection, err error) {
	buf := make([]*model.MqttConnection, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mqttConnectionDo) FindInBatches(result *[]*model.MqttConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mqttConnectionDo) Attrs(attrs ...field.AssignExpr) IMqttConnectionDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mqttConnectionDo) Assign(attrs ...field.AssignExpr) IMqttConnectionDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mqttConnectionDo) Joins(fields ...field.RelationField) IMqttConnectionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mqttConnectionDo) Preload(fields ...field.RelationField) IMqttConnectionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mqttConnectionDo) FirstOrInit() (*model.MqttConnection, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttConnection), nil
	}
}

func (m mqttConnectionDo) FirstOrCreate() (*model.MqttConnection, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttConnection), nil
	}
}

func (m mqttConnectionDo) FindByPage(offset int, limit int) (result []*model.MqttConnection, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mqttConnectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mqttConnectionDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mqttConnectionDo) Delete(models ...*model.MqttConnection) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mqttConnectionDo) withDO(do gen.Dao) *mqttConnectionDo {
	m.DO = *do.(*gen.DO)
	return m
}
