// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/internal/dao/model"
)

func newMqttMessage(db *gorm.DB, opts ...gen.DOOption) mqttMessage {
	_mqttMessage := mqttMessage{}

	_mqttMessage.mqttMessageDo.UseDB(db, opts...)
	_mqttMessage.mqttMessageDo.UseModel(&model.MqttMessage{})

	tableName := _mqttMessage.mqttMessageDo.TableName()
	_mqttMessage.ALL = field.NewAsterisk(tableName)
	_mqttMessage.ID = field.NewInt32(tableName, "id")
	_mqttMessage.ConnectionID = field.NewInt32(tableName, "connection_id")
	_mqttMessage.MsgType = field.NewString(tableName, "msg_type")
	_mqttMessage.Color = field.NewString(tableName, "color")
	_mqttMessage.Topic = field.NewString(tableName, "topic")
	_mqttMessage.Payload = field.NewString(tableName, "payload")
	_mqttMessage.Qos = field.NewInt32(tableName, "qos")
	_mqttMessage.Retain = field.NewInt32(tableName, "retain")
	_mqttMessage.SubscriptionIdentifiers = field.NewString(tableName, "subscription_identifiers")
	_mqttMessage.UserProperties = field.NewString(tableName, "user_properties")
	_mqttMessage.ResponseTopic = field.NewString(tableName, "response_topic")
	_mqttMessage.ContentType = field.NewString(tableName, "content_type")
	_mqttMessage.CorrelationData = field.NewString(tableName, "correlation_data")
	_mqttMessage.MessageExpiry = field.NewInt32(tableName, "message_expiry")
	_mqttMessage.CreatedAt = field.NewTime(tableName, "created_at")

	_mqttMessage.fillFieldMap()

	return _mqttMessage
}

type mqttMessage struct {
	mqttMessageDo

	ALL                     field.Asterisk
	ID                      field.Int32
	ConnectionID            field.Int32
	MsgType                 field.String
	Color                   field.String
	Topic                   field.String
	Payload                 field.String
	Qos                     field.Int32
	Retain                  field.Int32
	SubscriptionIdentifiers field.String
	UserProperties          field.String
	ResponseTopic           field.String
	ContentType             field.String
	CorrelationData         field.String
	MessageExpiry           field.Int32
	CreatedAt               field.Time

	fieldMap map[string]field.Expr
}

func (m mqttMessage) Table(newTableName string) *mqttMessage {
	m.mqttMessageDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mqttMessage) As(alias string) *mqttMessage {
	m.mqttMessageDo.DO = *(m.mqttMessageDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mqttMessage) updateTableName(table string) *mqttMessage {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.ConnectionID = field.NewInt32(table, "connection_id")
	m.MsgType = field.NewString(table, "msg_type")
	m.Color = field.NewString(table, "color")
	m.Topic = field.NewString(table, "topic")
	m.Payload = field.NewString(table, "payload")
	m.Qos = field.NewInt32(table, "qos")
	m.Retain = field.NewInt32(table, "retain")
	m.SubscriptionIdentifiers = field.NewString(table, "subscription_identifiers")
	m.UserProperties = field.NewString(table, "user_properties")
	m.ResponseTopic = field.NewString(table, "response_topic")
	m.ContentType = field.NewString(table, "content_type")
	m.CorrelationData = field.NewString(table, "correlation_data")
	m.MessageExpiry = field.NewInt32(table, "message_expiry")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *mqttMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mqttMessage) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 15)
	m.fieldMap["id"] = m.ID
	m.fieldMap["connection_id"] = m.ConnectionID
	m.fieldMap["msg_type"] = m.MsgType
	m.fieldMap["color"] = m.Color
	m.fieldMap["topic"] = m.Topic
	m.fieldMap["payload"] = m.Payload
	m.fieldMap["qos"] = m.Qos
	m.fieldMap["retain"] = m.Retain
	m.fieldMap["subscription_identifiers"] = m.SubscriptionIdentifiers
	m.fieldMap["user_properties"] = m.UserProperties
	m.fieldMap["response_topic"] = m.ResponseTopic
	m.fieldMap["content_type"] = m.ContentType
	m.fieldMap["correlation_data"] = m.CorrelationData
	m.fieldMap["message_expiry"] = m.MessageExpiry
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m mqttMessage) clone(db *gorm.DB) mqttMessage {
	m.mqttMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mqttMessage) replaceDB(db *gorm.DB) mqttMessage {
	m.mqttMessageDo.ReplaceDB(db)
	return m
}

type mqttMessageDo struct{ gen.DO }

type IMqttMessageDo interface {
	gen.SubQuery
	Debug() IMqttMessageDo
	WithContext(ctx context.Context) IMqttMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMqttMessageDo
	WriteDB() IMqttMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMqttMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMqttMessageDo
	Not(conds ...gen.Condition) IMqttMessageDo
	Or(conds ...gen.Condition) IMqttMessageDo
	Select(conds ...field.Expr) IMqttMessageDo
	Where(conds ...gen.Condition) IMqttMessageDo
	Order(conds ...field.Expr) IMqttMessageDo
	Distinct(cols ...field.Expr) IMqttMessageDo
	Omit(cols ...field.Expr) IMqttMessageDo
	Join(table schema.Tabler, on ...field.Expr) IMqttMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMqttMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMqttMessageDo
	Group(cols ...field.Expr) IMqttMessageDo
	Having(conds ...gen.Condition) IMqttMessageDo
	Limit(limit int) IMqttMessageDo
	Offset(offset int) IMqttMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttMessageDo
	Unscoped() IMqttMessageDo
	Create(values ...*model.MqttMessage) error
	CreateInBatches(values []*model.MqttMessage, batchSize int) error
	Save(values ...*model.MqttMessage) error
	First() (*model.MqttMessage, error)
	Take() (*model.MqttMessage, error)
	Last() (*model.MqttMessage, error)
	Find() ([]*model.MqttMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttMessage, err error)
	FindInBatches(result *[]*model.MqttMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MqttMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMqttMessageDo
	Assign(attrs ...field.AssignExpr) IMqttMessageDo
	Joins(fields ...field.RelationField) IMqttMessageDo
	Preload(fields ...field.RelationField) IMqttMessageDo
	FirstOrInit() (*model.MqttMessage, error)
	FirstOrCreate() (*model.MqttMessage, error)
	FindByPage(offset int, limit int) (result []*model.MqttMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMqttMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mqttMessageDo) Debug() IMqttMessageDo {
	return m.withDO(m.DO.Debug())
}

func (m mqttMessageDo) WithContext(ctx context.Context) IMqttMessageDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mqttMessageDo) ReadDB() IMqttMessageDo {
	return m.Clauses(dbresolver.Read)
}

func (m mqttMessageDo) WriteDB() IMqttMessageDo {
	return m.Clauses(dbresolver.Write)
}

func (m mqttMessageDo) Session(config *gorm.Session) IMqttMessageDo {
	return m.withDO(m.DO.Session(config))
}

func (m mqttMessageDo) Clauses(conds ...clause.Expression) IMqttMessageDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mqttMessageDo) Returning(value interface{}, columns ...string) IMqttMessageDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mqttMessageDo) Not(conds ...gen.Condition) IMqttMessageDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mqttMessageDo) Or(conds ...gen.Condition) IMqttMessageDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mqttMessageDo) Select(conds ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mqttMessageDo) Where(conds ...gen.Condition) IMqttMessageDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mqttMessageDo) Order(conds ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mqttMessageDo) Distinct(cols ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mqttMessageDo) Omit(cols ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mqttMessageDo) Join(table schema.Tabler, on ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mqttMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mqttMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mqttMessageDo) Group(cols ...field.Expr) IMqttMessageDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mqttMessageDo) Having(conds ...gen.Condition) IMqttMessageDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mqttMessageDo) Limit(limit int) IMqttMessageDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mqttMessageDo) Offset(offset int) IMqttMessageDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mqttMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttMessageDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mqttMessageDo) Unscoped() IMqttMessageDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mqttMessageDo) Create(values ...*model.MqttMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mqttMessageDo) CreateInBatches(values []*model.MqttMessage, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mqttMessageDo) Save(values ...*model.MqttMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mqttMessageDo) First() (*model.MqttMessage, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessage), nil
	}
}

func (m mqttMessageDo) Take() (*model.MqttMessage, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessage), nil
	}
}

func (m mqttMessageDo) Last() (*model.MqttMessage, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessage), nil
	}
}

func (m mqttMessageDo) Find() ([]*model.MqttMessage, error) {
	result, err := m.DO.Find()
	return result.([]*model.MqttMessage), err
}

func (m mqttMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttMessage, err error) {
	buf := make([]*model.MqttMessage, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mqttMessageDo) FindInBatches(result *[]*model.MqttMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mqttMessageDo) Attrs(attrs ...field.AssignExpr) IMqttMessageDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mqttMessageDo) Assign(attrs ...field.AssignExpr) IMqttMessageDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mqttMessageDo) Joins(fields ...field.RelationField) IMqttMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mqttMessageDo) Preload(fields ...field.RelationField) IMqttMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mqttMessageDo) FirstOrInit() (*model.MqttMessage, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessage), nil
	}
}

func (m mqttMessageDo) FirstOrCreate() (*model.MqttMessage, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttMessage), nil
	}
}

func (m mqttMessageDo) FindByPage(offset int, limit int) (result []*model.MqttMessage, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mqttMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mqttMessageDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mqttMessageDo) Delete(models ...*model.MqttMessage) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mqttMessageDo) withDO(do gen.Dao) *mqttMessageDo {
	m.DO = *do.(*gen.DO)
	return m
}
