// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/internal/dao/model"
)

func newMqttSubscription(db *gorm.DB, opts ...gen.DOOption) mqttSubscription {
	_mqttSubscription := mqttSubscription{}

	_mqttSubscription.mqttSubscriptionDo.UseDB(db, opts...)
	_mqttSubscription.mqttSubscriptionDo.UseModel(&model.MqttSubscription{})

	tableName := _mqttSubscription.mqttSubscriptionDo.TableName()
	_mqttSubscription.ALL = field.NewAsterisk(tableName)
	_mqttSubscription.ID = field.NewInt32(tableName, "id")
	_mqttSubscription.ConnectionID = field.NewInt32(tableName, "connection_id")
	_mqttSubscription.Topic = field.NewString(tableName, "topic")
	_mqttSubscription.Qos = field.NewInt32(tableName, "qos")
	_mqttSubscription.Color = field.NewString(tableName, "color")
	_mqttSubscription.Alias_ = field.NewString(tableName, "alias")
	_mqttSubscription.SubscriptionIdentifier = field.NewInt32(tableName, "subscription_identifier")
	_mqttSubscription.Nl = field.NewInt32(tableName, "nl")
	_mqttSubscription.Rap = field.NewInt32(tableName, "rap")
	_mqttSubscription.Rh = field.NewInt32(tableName, "rh")
	_mqttSubscription.Disabled = field.NewInt32(tableName, "disabled")
	_mqttSubscription.CreatedAt = field.NewTime(tableName, "created_at")
	_mqttSubscription.UpdatedAt = field.NewTime(tableName, "updated_at")

	_mqttSubscription.fillFieldMap()

	return _mqttSubscription
}

type mqttSubscription struct {
	mqttSubscriptionDo

	ALL                    field.Asterisk
	ID                     field.Int32
	ConnectionID           field.Int32
	Topic                  field.String
	Qos                    field.Int32
	Color                  field.String
	Alias_                 field.String
	SubscriptionIdentifier field.Int32
	Nl                     field.Int32
	Rap                    field.Int32
	Rh                     field.Int32
	Disabled               field.Int32
	CreatedAt              field.Time
	UpdatedAt              field.Time

	fieldMap map[string]field.Expr
}

func (m mqttSubscription) Table(newTableName string) *mqttSubscription {
	m.mqttSubscriptionDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mqttSubscription) As(alias string) *mqttSubscription {
	m.mqttSubscriptionDo.DO = *(m.mqttSubscriptionDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mqttSubscription) updateTableName(table string) *mqttSubscription {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.ConnectionID = field.NewInt32(table, "connection_id")
	m.Topic = field.NewString(table, "topic")
	m.Qos = field.NewInt32(table, "qos")
	m.Color = field.NewString(table, "color")
	m.Alias_ = field.NewString(table, "alias")
	m.SubscriptionIdentifier = field.NewInt32(table, "subscription_identifier")
	m.Nl = field.NewInt32(table, "nl")
	m.Rap = field.NewInt32(table, "rap")
	m.Rh = field.NewInt32(table, "rh")
	m.Disabled = field.NewInt32(table, "disabled")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *mqttSubscription) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mqttSubscription) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 13)
	m.fieldMap["id"] = m.ID
	m.fieldMap["connection_id"] = m.ConnectionID
	m.fieldMap["topic"] = m.Topic
	m.fieldMap["qos"] = m.Qos
	m.fieldMap["color"] = m.Color
	m.fieldMap["alias"] = m.Alias_
	m.fieldMap["subscription_identifier"] = m.SubscriptionIdentifier
	m.fieldMap["nl"] = m.Nl
	m.fieldMap["rap"] = m.Rap
	m.fieldMap["rh"] = m.Rh
	m.fieldMap["disabled"] = m.Disabled
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m mqttSubscription) clone(db *gorm.DB) mqttSubscription {
	m.mqttSubscriptionDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mqttSubscription) replaceDB(db *gorm.DB) mqttSubscription {
	m.mqttSubscriptionDo.ReplaceDB(db)
	return m
}

type mqttSubscriptionDo struct{ gen.DO }

type IMqttSubscriptionDo interface {
	gen.SubQuery
	Debug() IMqttSubscriptionDo
	WithContext(ctx context.Context) IMqttSubscriptionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMqttSubscriptionDo
	WriteDB() IMqttSubscriptionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMqttSubscriptionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMqttSubscriptionDo
	Not(conds ...gen.Condition) IMqttSubscriptionDo
	Or(conds ...gen.Condition) IMqttSubscriptionDo
	Select(conds ...field.Expr) IMqttSubscriptionDo
	Where(conds ...gen.Condition) IMqttSubscriptionDo
	Order(conds ...field.Expr) IMqttSubscriptionDo
	Distinct(cols ...field.Expr) IMqttSubscriptionDo
	Omit(cols ...field.Expr) IMqttSubscriptionDo
	Join(table schema.Tabler, on ...field.Expr) IMqttSubscriptionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMqttSubscriptionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMqttSubscriptionDo
	Group(cols ...field.Expr) IMqttSubscriptionDo
	Having(conds ...gen.Condition) IMqttSubscriptionDo
	Limit(limit int) IMqttSubscriptionDo
	Offset(offset int) IMqttSubscriptionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttSubscriptionDo
	Unscoped() IMqttSubscriptionDo
	Create(values ...*model.MqttSubscription) error
	CreateInBatches(values []*model.MqttSubscription, batchSize int) error
	Save(values ...*model.MqttSubscription) error
	First() (*model.MqttSubscription, error)
	Take() (*model.MqttSubscription, error)
	Last() (*model.MqttSubscription, error)
	Find() ([]*model.MqttSubscription, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttSubscription, err error)
	FindInBatches(result *[]*model.MqttSubscription, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MqttSubscription) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMqttSubscriptionDo
	Assign(attrs ...field.AssignExpr) IMqttSubscriptionDo
	Joins(fields ...field.RelationField) IMqttSubscriptionDo
	Preload(fields ...field.RelationField) IMqttSubscriptionDo
	FirstOrInit() (*model.MqttSubscription, error)
	FirstOrCreate() (*model.MqttSubscription, error)
	FindByPage(offset int, limit int) (result []*model.MqttSubscription, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMqttSubscriptionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mqttSubscriptionDo) Debug() IMqttSubscriptionDo {
	return m.withDO(m.DO.Debug())
}

func (m mqttSubscriptionDo) WithContext(ctx context.Context) IMqttSubscriptionDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mqttSubscriptionDo) ReadDB() IMqttSubscriptionDo {
	return m.Clauses(dbresolver.Read)
}

func (m mqttSubscriptionDo) WriteDB() IMqttSubscriptionDo {
	return m.Clauses(dbresolver.Write)
}

func (m mqttSubscriptionDo) Session(config *gorm.Session) IMqttSubscriptionDo {
	return m.withDO(m.DO.Session(config))
}

func (m mqttSubscriptionDo) Clauses(conds ...clause.Expression) IMqttSubscriptionDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mqttSubscriptionDo) Returning(value interface{}, columns ...string) IMqttSubscriptionDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mqttSubscriptionDo) Not(conds ...gen.Condition) IMqttSubscriptionDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mqttSubscriptionDo) Or(conds ...gen.Condition) IMqttSubscriptionDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mqttSubscriptionDo) Select(conds ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mqttSubscriptionDo) Where(conds ...gen.Condition) IMqttSubscriptionDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mqttSubscriptionDo) Order(conds ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mqttSubscriptionDo) Distinct(cols ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mqttSubscriptionDo) Omit(cols ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mqttSubscriptionDo) Join(table schema.Tabler, on ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mqttSubscriptionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mqttSubscriptionDo) RightJoin(table schema.Tabler, on ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mqttSubscriptionDo) Group(cols ...field.Expr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mqttSubscriptionDo) Having(conds ...gen.Condition) IMqttSubscriptionDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mqttSubscriptionDo) Limit(limit int) IMqttSubscriptionDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mqttSubscriptionDo) Offset(offset int) IMqttSubscriptionDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mqttSubscriptionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttSubscriptionDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mqttSubscriptionDo) Unscoped() IMqttSubscriptionDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mqttSubscriptionDo) Create(values ...*model.MqttSubscription) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mqttSubscriptionDo) CreateInBatches(values []*model.MqttSubscription, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mqttSubscriptionDo) Save(values ...*model.MqttSubscription) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mqttSubscriptionDo) First() (*model.MqttSubscription, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttSubscription), nil
	}
}

func (m mqttSubscriptionDo) Take() (*model.MqttSubscription, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttSubscription), nil
	}
}

func (m mqttSubscriptionDo) Last() (*model.MqttSubscription, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttSubscription), nil
	}
}

func (m mqttSubscriptionDo) Find() ([]*model.MqttSubscription, error) {
	result, err := m.DO.Find()
	return result.([]*model.MqttSubscription), err
}

func (m mqttSubscriptionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttSubscription, err error) {
	buf := make([]*model.MqttSubscription, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mqttSubscriptionDo) FindInBatches(result *[]*model.MqttSubscription, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mqttSubscriptionDo) Attrs(attrs ...field.AssignExpr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mqttSubscriptionDo) Assign(attrs ...field.AssignExpr) IMqttSubscriptionDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mqttSubscriptionDo) Joins(fields ...field.RelationField) IMqttSubscriptionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mqttSubscriptionDo) Preload(fields ...field.RelationField) IMqttSubscriptionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mqttSubscriptionDo) FirstOrInit() (*model.MqttSubscription, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttSubscription), nil
	}
}

func (m mqttSubscriptionDo) FirstOrCreate() (*model.MqttSubscription, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttSubscription), nil
	}
}

func (m mqttSubscriptionDo) FindByPage(offset int, limit int) (result []*model.MqttSubscription, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mqttSubscriptionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mqttSubscriptionDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mqttSubscriptionDo) Delete(models ...*model.MqttSubscription) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mqttSubscriptionDo) withDO(do gen.Dao) *mqttSubscriptionDo {
	m.DO = *do.(*gen.DO)
	return m
}
