// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/internal/dao/model"
)

func newMqttTopicRecord(db *gorm.DB, opts ...gen.DOOption) mqttTopicRecord {
	_mqttTopicRecord := mqttTopicRecord{}

	_mqttTopicRecord.mqttTopicRecordDo.UseDB(db, opts...)
	_mqttTopicRecord.mqttTopicRecordDo.UseModel(&model.MqttTopicRecord{})

	tableName := _mqttTopicRecord.mqttTopicRecordDo.TableName()
	_mqttTopicRecord.ALL = field.NewAsterisk(tableName)
	_mqttTopicRecord.ID = field.NewInt32(tableName, "id")
	_mqttTopicRecord.Qos = field.NewInt32(tableName, "qos")
	_mqttTopicRecord.Retain = field.NewInt32(tableName, "retain")
	_mqttTopicRecord.Topic = field.NewString(tableName, "topic")
	_mqttTopicRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_mqttTopicRecord.fillFieldMap()

	return _mqttTopicRecord
}

type mqttTopicRecord struct {
	mqttTopicRecordDo

	ALL       field.Asterisk
	ID        field.Int32
	Qos       field.Int32
	Retain    field.Int32
	Topic     field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (m mqttTopicRecord) Table(newTableName string) *mqttTopicRecord {
	m.mqttTopicRecordDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mqttTopicRecord) As(alias string) *mqttTopicRecord {
	m.mqttTopicRecordDo.DO = *(m.mqttTopicRecordDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mqttTopicRecord) updateTableName(table string) *mqttTopicRecord {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.Qos = field.NewInt32(table, "qos")
	m.Retain = field.NewInt32(table, "retain")
	m.Topic = field.NewString(table, "topic")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *mqttTopicRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mqttTopicRecord) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["qos"] = m.Qos
	m.fieldMap["retain"] = m.Retain
	m.fieldMap["topic"] = m.Topic
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m mqttTopicRecord) clone(db *gorm.DB) mqttTopicRecord {
	m.mqttTopicRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mqttTopicRecord) replaceDB(db *gorm.DB) mqttTopicRecord {
	m.mqttTopicRecordDo.ReplaceDB(db)
	return m
}

type mqttTopicRecordDo struct{ gen.DO }

type IMqttTopicRecordDo interface {
	gen.SubQuery
	Debug() IMqttTopicRecordDo
	WithContext(ctx context.Context) IMqttTopicRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMqttTopicRecordDo
	WriteDB() IMqttTopicRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMqttTopicRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMqttTopicRecordDo
	Not(conds ...gen.Condition) IMqttTopicRecordDo
	Or(conds ...gen.Condition) IMqttTopicRecordDo
	Select(conds ...field.Expr) IMqttTopicRecordDo
	Where(conds ...gen.Condition) IMqttTopicRecordDo
	Order(conds ...field.Expr) IMqttTopicRecordDo
	Distinct(cols ...field.Expr) IMqttTopicRecordDo
	Omit(cols ...field.Expr) IMqttTopicRecordDo
	Join(table schema.Tabler, on ...field.Expr) IMqttTopicRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMqttTopicRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMqttTopicRecordDo
	Group(cols ...field.Expr) IMqttTopicRecordDo
	Having(conds ...gen.Condition) IMqttTopicRecordDo
	Limit(limit int) IMqttTopicRecordDo
	Offset(offset int) IMqttTopicRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttTopicRecordDo
	Unscoped() IMqttTopicRecordDo
	Create(values ...*model.MqttTopicRecord) error
	CreateInBatches(values []*model.MqttTopicRecord, batchSize int) error
	Save(values ...*model.MqttTopicRecord) error
	First() (*model.MqttTopicRecord, error)
	Take() (*model.MqttTopicRecord, error)
	Last() (*model.MqttTopicRecord, error)
	Find() ([]*model.MqttTopicRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttTopicRecord, err error)
	FindInBatches(result *[]*model.MqttTopicRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MqttTopicRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMqttTopicRecordDo
	Assign(attrs ...field.AssignExpr) IMqttTopicRecordDo
	Joins(fields ...field.RelationField) IMqttTopicRecordDo
	Preload(fields ...field.RelationField) IMqttTopicRecordDo
	FirstOrInit() (*model.MqttTopicRecord, error)
	FirstOrCreate() (*model.MqttTopicRecord, error)
	FindByPage(offset int, limit int) (result []*model.MqttTopicRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMqttTopicRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mqttTopicRecordDo) Debug() IMqttTopicRecordDo {
	return m.withDO(m.DO.Debug())
}

func (m mqttTopicRecordDo) WithContext(ctx context.Context) IMqttTopicRecordDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mqttTopicRecordDo) ReadDB() IMqttTopicRecordDo {
	return m.Clauses(dbresolver.Read)
}

func (m mqttTopicRecordDo) WriteDB() IMqttTopicRecordDo {
	return m.Clauses(dbresolver.Write)
}

func (m mqttTopicRecordDo) Session(config *gorm.Session) IMqttTopicRecordDo {
	return m.withDO(m.DO.Session(config))
}

func (m mqttTopicRecordDo) Clauses(conds ...clause.Expression) IMqttTopicRecordDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mqttTopicRecordDo) Returning(value interface{}, columns ...string) IMqttTopicRecordDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mqttTopicRecordDo) Not(conds ...gen.Condition) IMqttTopicRecordDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mqttTopicRecordDo) Or(conds ...gen.Condition) IMqttTopicRecordDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mqttTopicRecordDo) Select(conds ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mqttTopicRecordDo) Where(conds ...gen.Condition) IMqttTopicRecordDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mqttTopicRecordDo) Order(conds ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mqttTopicRecordDo) Distinct(cols ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mqttTopicRecordDo) Omit(cols ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mqttTopicRecordDo) Join(table schema.Tabler, on ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mqttTopicRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mqttTopicRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mqttTopicRecordDo) Group(cols ...field.Expr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mqttTopicRecordDo) Having(conds ...gen.Condition) IMqttTopicRecordDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mqttTopicRecordDo) Limit(limit int) IMqttTopicRecordDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mqttTopicRecordDo) Offset(offset int) IMqttTopicRecordDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mqttTopicRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMqttTopicRecordDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mqttTopicRecordDo) Unscoped() IMqttTopicRecordDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mqttTopicRecordDo) Create(values ...*model.MqttTopicRecord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mqttTopicRecordDo) CreateInBatches(values []*model.MqttTopicRecord, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mqttTopicRecordDo) Save(values ...*model.MqttTopicRecord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mqttTopicRecordDo) First() (*model.MqttTopicRecord, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttTopicRecord), nil
	}
}

func (m mqttTopicRecordDo) Take() (*model.MqttTopicRecord, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttTopicRecord), nil
	}
}

func (m mqttTopicRecordDo) Last() (*model.MqttTopicRecord, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttTopicRecord), nil
	}
}

func (m mqttTopicRecordDo) Find() ([]*model.MqttTopicRecord, error) {
	result, err := m.DO.Find()
	return result.([]*model.MqttTopicRecord), err
}

func (m mqttTopicRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqttTopicRecord, err error) {
	buf := make([]*model.MqttTopicRecord, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mqttTopicRecordDo) FindInBatches(result *[]*model.MqttTopicRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mqttTopicRecordDo) Attrs(attrs ...field.AssignExpr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mqttTopicRecordDo) Assign(attrs ...field.AssignExpr) IMqttTopicRecordDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mqttTopicRecordDo) Joins(fields ...field.RelationField) IMqttTopicRecordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mqttTopicRecordDo) Preload(fields ...field.RelationField) IMqttTopicRecordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mqttTopicRecordDo) FirstOrInit() (*model.MqttTopicRecord, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttTopicRecord), nil
	}
}

func (m mqttTopicRecordDo) FirstOrCreate() (*model.MqttTopicRecord, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqttTopicRecord), nil
	}
}

func (m mqttTopicRecordDo) FindByPage(offset int, limit int) (result []*model.MqttTopicRecord, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mqttTopicRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mqttTopicRecordDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mqttTopicRecordDo) Delete(models ...*model.MqttTopicRecord) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mqttTopicRecordDo) withDO(do gen.Dao) *mqttTopicRecordDo {
	m.DO = *do.(*gen.DO)
	return m
}
