// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettingService 应用设置：开机自启 / 托盘 / 快捷键 / 运行目录 / 版本信息 / 启动恢复
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetAppInfo 应用信息（关于区使用）
 */
export function GetAppInfo(): $CancellablePromise<any> {
    return $Call.ByID(2345238691);
}

/**
 * GetAutoRestoreConnections 返回标记了"自动重连"的连接列表（启动恢复用）
 */
export function GetAutoRestoreConnections(): $CancellablePromise<any> {
    return $Call.ByID(3830675712);
}

/**
 * GetAutostart 获取开机自启状态
 */
export function GetAutostart(): $CancellablePromise<any> {
    return $Call.ByID(686319553);
}

/**
 * GetHotkeys 获取快捷键启用状态
 */
export function GetHotkeys(): $CancellablePromise<any> {
    return $Call.ByID(1653920063);
}

/**
 * GetRuntimeDir 返回运行时目录（日志/导出文件所在）
 */
export function GetRuntimeDir(): $CancellablePromise<any> {
    return $Call.ByID(2268162207);
}

/**
 * GetTrayMinimize 获取最小化到托盘状态
 */
export function GetTrayMinimize(): $CancellablePromise<any> {
    return $Call.ByID(341289556);
}

/**
 * OpenRuntimeDir 打开运行时目录（日志/导出文件所在）
 */
export function OpenRuntimeDir(): $CancellablePromise<any> {
    return $Call.ByID(1375059771);
}

/**
 * SetAutostart 设置开机自启
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<any> {
    return $Call.ByID(2622159605, enabled);
}

/**
 * SetHotkeys 注册/注销全局快捷键
 *   - Ctrl+Shift+H 显示/隐藏主窗口
 *   - Ctrl+Shift+D 断开全部连接
 *   - Ctrl+Shift+P 快速发布（事件 hotkey:publish，前端监听）
 */
export function SetHotkeys(enabled: boolean): $CancellablePromise<any> {
    return $Call.ByID(2969108307, enabled);
}

/**
 * SetTrayMinimize 设置关闭窗口时最小化到托盘（托盘常驻，见 main.go）
 */
export function SetTrayMinimize(enabled: boolean): $CancellablePromise<any> {
    return $Call.ByID(3952058896, enabled);
}
