// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ClearMessage 清除指定连接数据
 */
export function ClearMessage(id: number): $CancellablePromise<any> {
    return $Call.ByID(212125072, id);
}

/**
 * ClearRecord 清除主题和内容记录
 */
export function ClearRecord(): $CancellablePromise<any> {
    return $Call.ByID(3593441224);
}

/**
 * Del 删除数据
 */
export function Del(id: number): $CancellablePromise<any> {
    return $Call.ByID(780411305, id);
}

/**
 * GetContent 获取内容
 */
export function GetContent(id: number): $CancellablePromise<any> {
    return $Call.ByID(503630757, id);
}

/**
 * GetList 获取消息列表
 * cid 是connection表数据id，searchTopic是从订阅表获取的主题如：topic/#
 */
export function GetList(cid: number, searchTopic: string, msgType: string): $CancellablePromise<any> {
    return $Call.ByID(3960028872, cid, searchTopic, msgType);
}

/**
 * Save 保存/更新消息
 */
export function Save(param: string): $CancellablePromise<any> {
    return $Call.ByID(463059905, param);
}
