// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MqttGatewayService MQTT 网关模块
 * 
 * 采集任务运行在 MQTTW 进程内（方案 A）：进程退出即采集停止，无后台残留。
 * 退出前通过 StopGatewayOnExit() 显式停止，保证串口/连接立即释放、MQTT 遗嘱即时发出。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * BatchImportModbusPoints CSV 批量导入点位。
 * CSV 表头（可选，第一行含 name 则跳过）：
 * 
 * 	name,register_type,address,quantity,data_type,scale,offset,unit,topic_override,only_on_change
 */
export function BatchImportModbusPoints(deviceId: number, csvText: string): $CancellablePromise<any> {
    return $Call.ByID(3880666395, deviceId, csvText);
}

/**
 * DeleteModbusDevice 删除设备（级联删除其点位）
 */
export function DeleteModbusDevice(id: number): $CancellablePromise<any> {
    return $Call.ByID(2637758862, id);
}

/**
 * DeleteModbusPoint 删除点位
 */
export function DeleteModbusPoint(id: number): $CancellablePromise<any> {
    return $Call.ByID(2377752890, id);
}

/**
 * GetModbusGatewayStatus 网关运行状态快照
 */
export function GetModbusGatewayStatus(): $CancellablePromise<any> {
    return $Call.ByID(2674426195);
}

/**
 * ListGatewayBrokerOptions 可选 MQTT Broker 连接列表（设备表单下拉）
 */
export function ListGatewayBrokerOptions(): $CancellablePromise<any> {
    return $Call.ByID(3342270774);
}

/**
 * ListModbusDevices 设备列表
 */
export function ListModbusDevices(): $CancellablePromise<any> {
    return $Call.ByID(1934054670);
}

/**
 * ListModbusPoints 点位列表
 */
export function ListModbusPoints(deviceId: number): $CancellablePromise<any> {
    return $Call.ByID(3478661032, deviceId);
}

/**
 * SaveModbusDevice 新增/编辑设备（id>0 更新，否则新增）。
 * param: 前端 JSON（键名 camelCase 或 snake_case 均可）
 */
export function SaveModbusDevice(param: string): $CancellablePromise<any> {
    return $Call.ByID(2660573744, param);
}

/**
 * SaveModbusPoint 新增/编辑点位（id>0 更新，否则新增）
 */
export function SaveModbusPoint(param: string): $CancellablePromise<any> {
    return $Call.ByID(2268276608, param);
}

/**
 * StartModbusGateway 启动网关：所有 enabled 设备进入采集
 */
export function StartModbusGateway(): $CancellablePromise<any> {
    return $Call.ByID(1333475601);
}

/**
 * StopModbusGateway 停止网关
 */
export function StopModbusGateway(): $CancellablePromise<any> {
    return $Call.ByID(2744277727);
}

/**
 * TestReadModbus 在线读取测试（单次，不启动采集任务）
 */
export function TestReadModbus(deviceId: number): $CancellablePromise<any> {
    return $Call.ByID(342582479, deviceId);
}
