// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Copy 复制连接数据
 */
export function Copy(id: number): $CancellablePromise<any> {
    return $Call.ByID(2167819510, id);
}

/**
 * Del 删除数据
 */
export function Del(id: number): $CancellablePromise<any> {
    return $Call.ByID(395711592, id);
}

/**
 * GetContent 获取内容
 */
export function GetContent(id: number): $CancellablePromise<any> {
    return $Call.ByID(1023686966, id);
}

/**
 * GetInfo 获取指定字段内容
 */
export function GetInfo(id: number): $CancellablePromise<any> {
    return $Call.ByID(3799308169, id);
}

/**
 * GetList 获取连接/分组树
 */
export function GetList(): $CancellablePromise<any> {
    return $Call.ByID(2810637469);
}

/**
 * SaveData 保存/更新数据
 */
export function SaveData(param: string): $CancellablePromise<any> {
    return $Call.ByID(3694543778, param);
}

/**
 * SaveGroup 保存/更新分组数据
 */
export function SaveGroup(param: string): $CancellablePromise<any> {
    return $Call.ByID(559848837, param);
}

/**
 * Update 更新数据
 */
export function Update(param: string): $CancellablePromise<any> {
    return $Call.ByID(480427126, param);
}

/**
 * UpdateOrder 批量更新排序：pid（父级归属）+ weigh（同级顺序）
 * param 为 JSON 数组字符串：[{"id":1,"pid":0,"weigh":1},{"id":2,"pid":1,"weigh":1},...]
 * 前端拖拽结束后把整棵树扁平化传入（同层兄弟按位置编号 weigh=1,2,3...，根级 pid=0）
 */
export function UpdateOrder(param: string): $CancellablePromise<any> {
    return $Call.ByID(1304181486, param);
}
