// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * 客户端连接MQTT-Broker操作
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Connect 客户端连接MQTT服务器
 */
export function Connect(id: number): $CancellablePromise<any> {
    return $Call.ByID(1054204802, id);
}

/**
 * Disconnect 客户端断开连接
 */
export function Disconnect(id: number): $CancellablePromise<any> {
    return $Call.ByID(1281465798, id);
}

/**
 * DisconnectAll 断开全部在线客户端（全局快捷键 Ctrl+Shift+D 调用）
 */
export function DisconnectAll(): $CancellablePromise<any> {
    return $Call.ByID(2415928293);
}

/**
 * Publish 发布消息
 * param JSON 示例（payload 支持字符串或 JSON 对象；retain 支持 bool 或 0/1）：
 * 
 * 	{"connection_id":1,"topic":"t","payload":"{\"k\":1}","qos":0,"retain":false,
 * 	 "user_properties":[{"key":"k","value":"v"}],"response_topic":"","content_type":"",
 * 	 "correlation_data":"","message_expiry":0}
 */
export function Publish(param: string): $CancellablePromise<any> {
    return $Call.ByID(1314596591, param);
}

/**
 * Subscribe 订阅主题
 */
export function Subscribe(id: number): $CancellablePromise<any> {
    return $Call.ByID(3396504524, id);
}

/**
 * UnSubscribe 取消主题订阅
 * param JSON 示例：{"connection_id":1,"topic":"topic/#"}
 */
export function UnSubscribe(connection_id: number, topic: string): $CancellablePromise<any> {
    return $Call.ByID(2205373137, connection_id, topic);
}
