// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Del 删除数据
 */
export function Del(id: number): $CancellablePromise<any> {
    return $Call.ByID(4147506454, id);
}

/**
 * GetContent 获取内容
 */
export function GetContent(id: number): $CancellablePromise<any> {
    return $Call.ByID(4196008196, id);
}

/**
 * GetList 获取消息记录列表
 */
export function GetList(): $CancellablePromise<any> {
    return $Call.ByID(3612258603);
}

/**
 * Save 保存新消息记录
 */
export function Save(param: string): $CancellablePromise<any> {
    return $Call.ByID(4064992548, param);
}
