// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MqttStressService MQTT 压测（独立压测模块，不依赖调试客户端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ExportResult 导出压测结果 CSV 到 runtime/stress/
 */
export function ExportResult(): $CancellablePromise<any> {
    return $Call.ByID(3954087792);
}

/**
 * GetStatus 获取压测状态与实时指标快照
 */
export function GetStatus(): $CancellablePromise<any> {
    return $Call.ByID(3768446767);
}

/**
 * Start 启动压测任务
 * param: 前端 StressConfig 完整 JSON
 */
export function Start(param: string): $CancellablePromise<any> {
    return $Call.ByID(116845897, param);
}

/**
 * Stop 停止压测任务
 */
export function Stop(): $CancellablePromise<any> {
    return $Call.ByID(1779691747);
}
