// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Del 删除数据
 */
export function Del(id: number): $CancellablePromise<any> {
    return $Call.ByID(1482402339, id);
}

/**
 * Disable 禁用
 * status 禁用状态:0=正常,1=禁用
 */
export function Disable(id: number, status: number): $CancellablePromise<any> {
    return $Call.ByID(241201554, id, status);
}

/**
 * GetContent 获取内容
 */
export function GetContent(id: number): $CancellablePromise<any> {
    return $Call.ByID(913101287, id);
}

/**
 * GetList 获取订阅列表
 * cid 是connection表数据id
 */
export function GetList(cid: number): $CancellablePromise<any> {
    return $Call.ByID(3541982098, cid);
}

/**
 * Save 保存/更新订阅数据
 */
export function Save(param: string): $CancellablePromise<any> {
    return $Call.ByID(1762226647, param);
}
