// Code generated by gen_wails_service.go; DO NOT EDIT.
package service

import "github.com/wailsapp/wails/v3/pkg/application"

// NewAppServices 初始化所有服务，组装容器
func NewAppServices() []application.Service {
	return []application.Service{
		application.NewService(&AppSettingService{}),
		application.NewService(&MqttClientService{}),
		application.NewService(&MqttConnectionService{}),
		application.NewService(&MqttGatewayService{}),
		application.NewService(&MqttMessageRecordService{}),
		application.NewService(&MqttMessageService{}),
		application.NewService(&MqttStressService{}),
		application.NewService(&MqttSubscriptionService{}),
		application.NewService(&MqttTopicRecordService{}),
		application.NewService(&SystemService{}),
	}
}
