// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameModbusDevice = "modbus_device"

// ModbusDevice mapped from table <modbus_device>
type ModbusDevice struct {
	ID                 int32     `gorm:"column:id;primaryKey" json:"id"`
	Name               string    `gorm:"column:name;not null;default:''" json:"name"`
	Protocol           string    `gorm:"column:protocol;not null;default:'tcp'" json:"protocol"`
	Host               string    `gorm:"column:host;not null;default:''" json:"host"`
	Port               int32     `gorm:"column:port;not null;default:502" json:"port"`
	SlaveID            int32     `gorm:"column:slave_id;not null;default:1" json:"slave_id"`
	SerialPort         string    `gorm:"column:serial_port;not null;default:''" json:"serial_port"`
	BaudRate           int32     `gorm:"column:baud_rate;not null;default:9600" json:"baud_rate"`
	DataBits           int32     `gorm:"column:data_bits;not null;default:8" json:"data_bits"`
	StopBits           int32     `gorm:"column:stop_bits;not null;default:1" json:"stop_bits"`
	Parity             string    `gorm:"column:parity;not null;default:'none'" json:"parity"`
	PollInterval       int32     `gorm:"column:poll_interval;not null;default:1000" json:"poll_interval"`
	Timeout            int32     `gorm:"column:timeout;not null;default:1000" json:"timeout"`
	RetryCount         int32     `gorm:"column:retry_count;not null;default:3" json:"retry_count"`
	ByteOrder          string    `gorm:"column:byte_order;not null;default:'big'" json:"byte_order"`
	WordOrder          string    `gorm:"column:word_order;not null;default:'high_first'" json:"word_order"`
	BrokerConnectionID int32     `gorm:"column:broker_connection_id;not null" json:"broker_connection_id"`
	TopicPrefix        string    `gorm:"column:topic_prefix;not null;default:''" json:"topic_prefix"`
	Qos                int32     `gorm:"column:qos;not null" json:"qos"`
	Retain             int32     `gorm:"column:retain;not null" json:"retain"`
	AlarmTopic         string    `gorm:"column:alarm_topic;not null;default:''" json:"alarm_topic"`
	Enabled            int32     `gorm:"column:enabled;not null" json:"enabled"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ModbusDevice's table name
func (*ModbusDevice) TableName() string {
	return TableNameModbusDevice
}
