// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameModbusPoint = "modbus_point"

// ModbusPoint mapped from table <modbus_point>
type ModbusPoint struct {
	ID            int32     `gorm:"column:id;primaryKey" json:"id"`
	DeviceID      int32     `gorm:"column:device_id;not null" json:"device_id"`
	Name          string    `gorm:"column:name;not null;default:''" json:"name"`
	RegisterType  string    `gorm:"column:register_type;not null;default:'holding'" json:"register_type"`
	Address       int32     `gorm:"column:address;not null" json:"address"`
	Quantity      int32     `gorm:"column:quantity;not null;default:1" json:"quantity"`
	DataType      string    `gorm:"column:data_type;not null;default:'uint16'" json:"data_type"`
	Scale         float64   `gorm:"column:scale;not null;default:1" json:"scale"`
	Offset_       float64   `gorm:"column:offset;not null" json:"offset"`
	Unit          string    `gorm:"column:unit;not null;default:''" json:"unit"`
	TopicOverride string    `gorm:"column:topic_override;not null;default:''" json:"topic_override"`
	OnlyOnChange  int32     `gorm:"column:only_on_change;not null" json:"only_on_change"`
	Enabled       int32     `gorm:"column:enabled;not null;default:1" json:"enabled"`
	Sort          int32     `gorm:"column:sort;not null" json:"sort"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ModbusPoint's table name
func (*ModbusPoint) TableName() string {
	return TableNameModbusPoint
}
