// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMqttMessage = "mqtt_message"

// MqttMessage mapped from table <mqtt_message>
type MqttMessage struct {
	ID                      int32     `gorm:"column:id;primaryKey" json:"id"`
	ConnectionID            int32     `gorm:"column:connection_id;not null" json:"connection_id"`
	MsgType                 string    `gorm:"column:msg_type;not null;default:''" json:"msg_type"`
	Color                   string    `gorm:"column:color;not null;default:''" json:"color"`
	Topic                   string    `gorm:"column:topic;not null;default:''" json:"topic"`
	Payload                 string    `gorm:"column:payload;not null;default:''" json:"payload"`
	Qos                     int32     `gorm:"column:qos;not null" json:"qos"`
	Retain                  int32     `gorm:"column:retain;not null" json:"retain"`
	SubscriptionIdentifiers string    `gorm:"column:subscription_identifiers;not null;default:''" json:"subscription_identifiers"`
	UserProperties          string    `gorm:"column:user_properties;not null;default:''" json:"user_properties"`
	ResponseTopic           string    `gorm:"column:response_topic;not null;default:''" json:"response_topic"`
	ContentType             string    `gorm:"column:content_type;not null;default:''" json:"content_type"`
	CorrelationData         string    `gorm:"column:correlation_data;not null;default:''" json:"correlation_data"`
	MessageExpiry           int32     `gorm:"column:message_expiry;not null" json:"message_expiry"`
	CreatedAt               time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName MqttMessage's table name
func (*MqttMessage) TableName() string {
	return TableNameMqttMessage
}
