// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMqttTopicRecord = "mqtt_topic_record"

// MqttTopicRecord mapped from table <mqtt_topic_record>
type MqttTopicRecord struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	Qos       int32     `gorm:"column:qos;not null" json:"qos"`
	Retain    int32     `gorm:"column:retain;not null" json:"retain"`
	Topic     string    `gorm:"column:topic;not null;default:''" json:"topic"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName MqttTopicRecord's table name
func (*MqttTopicRecord) TableName() string {
	return TableNameMqttTopicRecord
}
