// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMqttMessageRecord = "mqtt_message_record"

// MqttMessageRecord mapped from table <mqtt_message_record>
type MqttMessageRecord struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	Payload     string    `gorm:"column:payload;not null;default:''" json:"payload"`
	PayloadType string    `gorm:"column:payload_type;not null;default:''" json:"payload_type"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName MqttMessageRecord's table name
func (*MqttMessageRecord) TableName() string {
	return TableNameMqttMessageRecord
}
