// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMqttSubscription = "mqtt_subscription"

// MqttSubscription mapped from table <mqtt_subscription>
type MqttSubscription struct {
	ID                     int32     `gorm:"column:id;primaryKey" json:"id"`
	ConnectionID           int32     `gorm:"column:connection_id;not null" json:"connection_id"`
	Topic                  string    `gorm:"column:topic;not null;default:''" json:"topic"`
	Qos                    int32     `gorm:"column:qos;not null" json:"qos"`
	Color                  string    `gorm:"column:color;not null;default:''" json:"color"`
	Alias_                 string    `gorm:"column:alias;not null;default:''" json:"alias"`
	SubscriptionIdentifier int32     `gorm:"column:subscription_identifier" json:"subscription_identifier"`
	Nl                     int32     `gorm:"column:nl;not null" json:"nl"`
	Rap                    int32     `gorm:"column:rap;not null" json:"rap"`
	Rh                     int32     `gorm:"column:rh;not null" json:"rh"`
	Disabled               int32     `gorm:"column:disabled;not null" json:"disabled"`
	CreatedAt              time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName MqttSubscription's table name
func (*MqttSubscription) TableName() string {
	return TableNameMqttSubscription
}
