// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMqttConnection = "mqtt_connection"

// MqttConnection mapped from table <mqtt_connection>
type MqttConnection struct {
	ID              int32     `gorm:"column:id;primaryKey" json:"id"`
	Title           string    `gorm:"column:title;not null" json:"title"`
	Pid             int32     `gorm:"column:pid;not null" json:"pid"`
	IsGroup         int32     `gorm:"column:is_group;not null" json:"is_group"`
	Protocol        string    `gorm:"column:protocol;not null" json:"protocol"`
	Host            string    `gorm:"column:host;not null" json:"host"`
	Port            string    `gorm:"column:port;not null" json:"port"`
	ClientID        string    `gorm:"column:client_id;not null" json:"client_id"`
	Path            string    `gorm:"column:path;not null" json:"path"`
	Username        string    `gorm:"column:username;not null" json:"username"`
	Password        string    `gorm:"column:password;not null" json:"password"`
	Ssl             int32     `gorm:"column:ssl;not null" json:"ssl"`
	SslSecurity     int32     `gorm:"column:ssl_security;not null" json:"ssl_security"`
	Alpn            string    `gorm:"column:alpn;not null" json:"alpn"`
	CertType        string    `gorm:"column:cert_type;not null" json:"cert_type"`
	Ca              string    `gorm:"column:ca;not null" json:"ca"`
	Cert            string    `gorm:"column:cert;not null" json:"cert"`
	Key             string    `gorm:"column:key;not null" json:"key"`
	MqttVersion     string    `gorm:"column:mqtt_version;not null" json:"mqtt_version"`
	ConnectTimeout  int32     `gorm:"column:connect_timeout;not null" json:"connect_timeout"`
	Keepalive       int32     `gorm:"column:keepalive;not null" json:"keepalive"`
	Reconnect       int32     `gorm:"column:reconnect;not null" json:"reconnect"`
	ReconnectPeriod int32     `gorm:"column:reconnect_period;not null" json:"reconnect_period"`
	Clean           int32     `gorm:"column:clean;not null" json:"clean"`
	Properties      string    `gorm:"column:properties;not null" json:"properties"`
	Will            string    `gorm:"column:will;not null" json:"will"`
	UserProperties  string    `gorm:"column:user_properties;not null" json:"user_properties"`
	Weigh           int32     `gorm:"column:weigh;not null;default:1" json:"weigh"`
	Connected       int32     `gorm:"column:connected;not null" json:"connected"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName MqttConnection's table name
func (*MqttConnection) TableName() string {
	return TableNameMqttConnection
}
