// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	Username  string    `gorm:"column:username;not null" json:"username"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Salt      string    `gorm:"column:salt;not null" json:"salt"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Role      string    `gorm:"column:role;not null" json:"role"`
	Email     string    `gorm:"column:email;not null;default:''" json:"email"`
	Remark    string    `gorm:"column:remark;not null" json:"remark"`
	Status    []byte    `gorm:"column:status;not null;default:0" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
